[paths]
# path to folder containing Aguichine models
path_folder_models = ../smint_models/

# saving path (OR path to chains if run_fit==False)
outputdir = ../smint_results/
# identifier for this fit (used for saving)
fname = test_irrowev_example

[physical params]
# Mass in Earth units
# if use_KDE_for_Mp_prior is True, used only to initialize Mp walkers
Mp_earth = 1.64
err_Mp_earth = 0.07

# if True, use kernel density estimation instead of Gaussian prior on the mass
use_KDE_for_Mp_prior = False
# paths to npy files that contain the x values (points) and the kde (density) at these points
path_file_kde_points = ../input_files/kde_points.npy
path_file_kde_density = ../input_files/kde_density.npy

# Radius in Earth units
Rp_earth = 1.627
err_Rp_earth = 0.041

## The physical parameters below are only needed for irr. ocean worlds models (irrow)
# irradiation temperature
Tirr = 566.92689046970
err_Tirr = 8.769637059273295

## The physical parameters below are only needed for the irr. ocean worlds evolution model (irrowev)
# equilibrium temperature
Teq = 416
err_Teq = 9
# stellar type (M or G)
stellar_type = M
# To get radius at 20 mbar write as R_20mbar, for radius at 1 microbar write as R_1mibar)
radius_pressure = R_20mbar

## The physical parameters below are not needed for a fit of the H2O fraction
# incident flux at the planet in units of the solar constant
Sinc_earth = 4.97
err_Sinc_earth = 0.52

# system params
# for a flat prior on the age (used if flat_age==True)
# lower bound (inf) and upper bound (sup)
age_Gyr_inf = 6.7
age_Gyr_sup = 8.6

# alternatively, for a gaussian prior (used if flat_age==False)
# median and std of gaussian prior
age_Gyr = 4.94
err_age_Gyr = 0.28

[MCMC params]
## The MCMC parameters below are not needed for a fit other than H2He and irrowev
# if True, use flat prior on star's age
flat_age = False

## The MCMC parameters below are not needed for a fit other than H2He
# if True, prior on fenv uniform on log10 (for the Lopez & Fortney models)
log_fenv_prior = False

## The MCMC parameters below are not needed for a fit other than irrow
# minimum irradiation temperature for the prior (in K), default is 400. Below assumed to be 400 K.
Tirr_min = 400.

## The MCMC parameters below are not needed for a fit other than irrowev
# minimum equilibrium temperature for the prior (in K), default is 400. Anything lower assumed to be 400 K.
Teq_min = 400.

## The parameters below are needed for all fits
# number of MCMC steps [for testing, for analysis use much more e.g. 10000]
nsteps = 1000
# number of MCMC walkers
nwalkers = 100

# if True, runs the MCMC; otherwise, postprocess an existing fit
# for post processing to work properly, path_folder_models, stellar_type, and radius_pressure must be checked even if no fit is run
run_fit = True
# fraction of the chains to be discarded as burn-in [0-1]
frac_burnin = 0.6


[plotting]
## The plotting parameters below are not needed for a fit of the H2He fraction
# color in histograms and corner plots
hist_color = b
# if True, generate corner plot
plot_corner = True

## The plotting parameters below are not needed for a fit of the H2O fraction
# color in histograms for metallicity = 1*solar and 50*solar
met1_color = b
met50_color = g

# if True, plot individual corner plots for each fit
corner_indiv = True
# if True, plot both corner plots superimposed
corner_both = True
# if True, plot mass radius curves
plot_mass_radius = True